# Generated by Django 4.2.7 on 2023-11-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=250)),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='A', max_length=1)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='A', max_length=1)),
                ('Book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('Book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
        ),
    ]
