# Generated by Django 4.2.7 on 2023-11-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Borrowed')], default='A', max_length=1),
        ),
    ]
