# Generated by Django 4.2.7 on 2023-11-23 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_requests',
        ),
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.AddField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.customer'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.author'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
        ),
    ]
