# Generated by Django 4.2.7 on 2023-11-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
